proxy:
  build: nginx/
  ports:
   - "80:80"
  links:
   - appinstance1
   - appinstance2
  hostname: "proxy"
  
appinstance1:
  build: tomcat/
  expose:
   - "8080"
  ports:
   - "8180:8080"
  links:
   - nosqldb
   #- elk
  hostname: "appinstance1"

appinstance2:
  build: tomcat/
  expose:
   - "8080"
  ports:
   - "8280:8080"
  links:
   - nosqldb
  # - elk
  hostname: "appinstance2"

nosqldb:
  build: mongo/
  hostname: "nosqldb"
  volumes:
   - "/opt/mongodb:/data/db"

#diable for comnarison with VirtualBox
#elk:
#  build: elk/
#  ports:
#   - "8081:80"
#   - "8082:9200"
#  expose:
#   - "5000/upd"
#  hostname: "elk" 
#
#logspout:
#  build: logspout/
#  volumes:
#   - "/var/run/docker.sock:/tmp/docker.sock"
#  links:
#   - elk
#  ports:
#   - "8083:8000"
#  environment:
#    - ROUTE_URIS=logstash://elk:5000
